### ISSUE TITLE
Change sort order of previous/next links

### ISSUE THREAD

**Issue by Wattaged** [CrossEye/TW5-WizardNav#3]
Can I change the sort order on the ‘next’ and ‘previous’ titles? At the moment they’re sorted alphabetically by title. I’d like to be able to step through by date created or any other field. 

Thanks for the plugin!

**Comment by CrossEye** [comment]
Solved in [0.5.0](https://crosseye.github.io/TW5-WizardNav/0.5.0/).

**Comment by CrossEye** [comment]
...and I already have the idea for a better solution.  Stat tuned.
